name: CI Build

on:
  push:
    branches: [ main ]
    tags: '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Pack & Push
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          VERSION_WITHOUT_V=${GITHUB_REF_NAME#v}
          dotnet pack -c Release -o dist -p:Version=$VERSION_WITHOUT_V
          dotnet nuget push dist/dotenv-tool.$VERSION_WITHOUT_V.nupkg --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
